name: TryPipeline
on:
  [push, workflow_dispatch]

jobs:
  apiRobotTest:
    name: Robot - API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotFramework
          pip install robotFramework-seleniumLibrary
          pip install robotFramework-requests
      - name: Start Test
        run: |
          python -m robot -i api test/RobotFrameWork/tc.robot

  postman:
    name: Postman Tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run NewMan
        run: |
          docker pull reportportal/newman     
          docker run -t reportportal/newman run https://raw.githubusercontent.com/lukastrilety/gitHubWorkShop/master/test/Postman/TestApi.json

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gitleaks
        # You may pin to the exact commit or the version.
        # uses: gitleaks/gitleaks-action@5425999620c418539c61a8143f29e346d5f6cf08
        uses: gitleaks/gitleaks-action@v2.2.0

  k6LoadTest:
    name: k6 Load Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ${{ github.workspace }}/test/k6/loadtest.js
          flags: --vus 50 --duration 10s
  siteSpeedIO:
    needs: [k6LoadTest, gitleaks, postman, apiRobotTest]
    name: Site speed IO
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: SiteSpeed.IO run
        run: |
          docker run --shm-size=1g --rm sitespeedio/sitespeed.io https://github.com/procesor2017/gitHubWorkShop -b chrome
