name: TryPipeline
on:
  [push, workflow_dispatch]

jobs:
  apiRobotTest:
    name: Robot - API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotFramework
          pip install robotFramework-seleniumLibrary
          pip install robotFramework-requests
      - name: Start Test
        run: |
          python -m robot -i api test/RobotFrameWork/tc.robot
  postman:
    name: Postman Tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run NewMan
        run: |
          docker pull reportportal/newman     
          docker run -t reportportal/newman run https://raw.githubusercontent.com/lukastrilety/gitHubWorkShop/master/test/Postman/TestApi.json
